web:
  image: ckpt/web-frontend
  ports:
    - "8080:80"
  links:
    - api:api.ckpt.no
api:
  image: ckpt/backend-services
  ports:
    - "8000:8000"
  links:
    - redis
redis:
  image: redis
  volumes:
    - data/:/data
    - conf/redis.conf:/usr/local/etc/redis/redis.conf
  command: redis-server /usr/local/etc/redis/redis.conf
