web:
  image: ckpt/web-frontend
  ports:
    - "127.0.0.1:8888:80"
api:
  env_file: .env
  image: ckpt/backend-services
  ports:
    - "8000:8000"
  links:
    - redis
    - rabbitmq
redis:
  image: redis
  volumes:
    - ./data/:/data
    - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
  command: redis-server /usr/local/etc/redis/redis.conf
rabbitmq:
  image: rabbitmq
  environment:
    - HOSTNAME: ckpt-rabbitmq
